### ISSUE TITLE
Scopes inside functions require return

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#105]
When using any sort of code that creates a new scope inside a function scope, the type checker requires a return such as:
```js
class Byte [value:list[Bit]] {
	let pub toString = [] -> str {
		let out = ""
		for (bit in value) {
			var out = out + bit.toString()
		}
		return out
	}
}
```
Will cause the type checker to throw
```
Error: The function return type of a str is unable to support the default return of () [maybe you forgot a return].
  --> binary.n:15:28
15 |         for (bit in value) {
16 |             var out = out + bit.toString()
17 |         }
Ran with 1 error and 0 warnings
```
This also occurs with `if` statements

**Comment by SheepTester** [comment]
quite interesting

**Comment by Ashvin-Ranjan** [comment]
It is clear that it has to do with this section of code
https://github.com/nbuilding/N-lang/blob/67f7755f1dcdc112b72ea36da380abead1e76349/python/scope.py#L1091-L1111

**Comment by SheepTester** [comment]
It's probably because of line 1101,

```py
parent_function = self.get_parent_function() 
```

Since it searches up the chain of parent scopes, inner scopes will think that they're *the* scope for the function. Probably this check should be done one step higher where function expressions are type checked
