### ISSUE TITLE
Add version flag to all versions of N

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#119]
It is hard to check what version of N you are running so `--version` would be a useful addition to add to all versions.

**Comment by SheepTester** [comment]
perhaps also `-v` and `-V`?

**Comment by Ashvin-Ranjan** [comment]
That seems useful as well

**Comment by SheepTester** [comment]
tfw you do `python -v` and it starts screaming wildly and you have no idea what you did wrong until you realize `-v` is `--verbose` not `--version` 😔

**Comment by Ashvin-Ranjan** [comment]
closed as of #165
