### ISSUE TITLE
Else if does not work, and if statements cannot be stacked.

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#124]
The main problem is that `else if` does not work as it will throw the error
```
Error: Internal problem: I only deal with instructions, not if.
--> test.n:1:16
1 |         } else if true {
2 |             // some code
3 |         }
Ran with 1 error and 0 warnings
```
and stacking if statements like so:
```js
if false {
  // some code
} if true {
  // some code
}
```
will cause a syntax error because `if` is a command, so there needs to be a newline or `;` separating them

**Comment by Ashvin-Ranjan** [comment]
This appears to be that, else if requires a else at the end actually

**Comment by SheepTester** [comment]
that's probably also a bug oop

**Comment by SheepTester** [comment]
For else if, here's where it runs the else branch. It calls `type_check_command` with `if_false`, which is from the children of `ifelse`.

https://github.com/nbuilding/N-lang/blob/c5dc02b0b703fa5791ffc108b210e24e5dfb506f/python/scope.py#L1932

If you look at the definition for `type_check_command`,

https://github.com/nbuilding/N-lang/blob/c5dc02b0b703fa5791ffc108b210e24e5dfb506f/python/scope.py#L1662-L1688

you can see where the `Internal problem: I only deal with instructions, not` internal problem comes from. Evidently, `if_false` is not a `code_block` nor an `instruction`. Then what is it?

If you look at the syntax,

https://github.com/nbuilding/N-lang/blob/c5dc02b0b703fa5791ffc108b210e24e5dfb506f/python/syntax.lark#L31

you can see that `if_false` is either an `instruction`, `code_block`, `ifelse`, or `if`. However,  `type_check_command` can only deal with the first two.

There's two solutions here:

- Make `type_check_command` able to handle `if` and `ifelse`.
- Check if `if_false` is `if` or `ifelse`, and if so, somehow convert it into an `instruction`.

You also should make sure that else if works as an expression as well.

**Comment by SheepTester** [comment]
For allowing `if cond { } if cond { }`, you'll have to modify the syntax. The syntax requires a semicolon or newline between instructions such as if statements:

https://github.com/nbuilding/N-lang/blob/c5dc02b0b703fa5791ffc108b210e24e5dfb506f/python/syntax.lark#L1

However, in this case, there is no newline or semicolon.

Perhaps instead, we can move that semicolon/newline requirement to this definition:

https://github.com/nbuilding/N-lang/blob/c5dc02b0b703fa5791ffc108b210e24e5dfb506f/python/syntax.lark#L3-L15

so it's something like

```lark
instruction: declare (";" | "\n")
           | function_callback (";" | "\n")
           | function_callback_pipe (";" | "\n")
           | for (";" | "\n")?
           | for_legacy (";" | "\n")?
           | ...
```

and then we can make that semicolon or newline optional after instructions with curly brackets.
