### ISSUE TITLE
A function with no arguments that returns an int is a different type than "int"

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#153]
The way to confirm this is by doing
```js
let test:{ test: int } = {
  test: [] -> int {
    return 2
  }
}
```
even though this should work it does not, this is most likely caused by the `int` typing of the function being stored in a `Function` class

**Comment by SheepTester** [comment]
Maybe functions with no arguments can act as an IIFE that returns immediately

**Comment by Ashvin-Ranjan** [comment]
That seems like the way to do
