### ISSUE TITLE
Cannot reference type or constructor within class

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#155]
```js
class Test [] {
  let pub clone = [] -> Test {
    return Test()
  }
}
```
This will cause two errors one being that the type `Test` is not defined and the other being that `Test()` is not defined, this is a problem for many different classes.

**Comment by SheepTester** [comment]
We might have to intellectually hold off on type checking a class or function body until a scope is done being type checked, then type check all the class and function expression bodies. We could add the function bodies to some list stored as a `Scope` property

**Comment by SheepTester** [comment]
> I guess maybe we can make an empty class type and then add methods/properties

[2021-05-20](https://discord.com/channels/710932856251351111/710936824121655396/845040695353540618)

**Comment by SheepTester** [comment]
> **!!!!** — 24/05/2021
> can't we create the class type immediately

> **ᚣ∫ᚱᚣ** — 24/05/2021
> yes but we need to have all of the methods in the class
> before we can create the type
> and that means we have to type check them
> which means we have to create the type class to check it
> and go back to step 1

> **!!!!** — 24/05/2021
> lol
> well
> we can edit the class type as we go
> :sunglasses:

...

> **ᚣ∫ᚱᚣ** — 24/05/2021
> what happens when
> ```js
> class Test [int wheee] {
>   let pub add = [t:Test] -> Test {
>     return Test(wheee + t.getWheee())
>   }
> 
>   let pub getWheee = [] -> int {
>     return wheee
>   }
> }
> ```

> !!!! — 24/05/2021
> well
> immediately at the start
> hmm
> we can defer function expression body type checking
> So
> At the start, we can make a new type `Test` with no properties/methods yet defined
> and then also make a new variable with the same name `Test` set to a function `int -> Test` (from the constructor arguments)
> then when we do
> ```ts
>   let pub add = [t:Test] -> Test {
>     return Test(wheee + t.getWheee())
>   }
> ```
> we already have the function type from the function expression header `[t:Test] -> Test`, so `Test`'s `add` property is `Test -> Test`
> and then we can defer type checking `{
>     return Test(wheee + t.getWheee())
>   }` to the end of the class statement

[2021-05-24](https://discord.com/channels/710932856251351111/710936824121655396/846489094950223983)

**Comment by SheepTester** [comment]
> **ᚣ∫ᚱᚣ** — 27/05/2021
> @!!!! can you help with https://github.com/nbuilding/N-lang/issues/155 because i have a general idea on how to do it i just need like a bit of help
> mostly just like we can make the type before we type check the class, but we need to make an outline of it first, which requires getting the types of all of the public fields in the class
> without having them throw errors when type checked

...

> **!!!!** — 27/05/2021
> how does class type checking work again
> https://github.com/nbuilding/N-lang/blob/bf22f049ca688105fe3553496de0233bc88ac39f/python/scope.py#L2012-L2062

...

> **ᚣ∫ᚱᚣ** — 27/05/2021
> it creates a new scope and yeah
> just that
> then it creates the type after it checks the scope

> **!!!!** — 27/05/2021
> yeah

> **ᚣ∫ᚱᚣ** — 27/05/2021
> so we can change that

> **!!!!** — 27/05/2021
> what if we created the type before checking the scope

> **ᚣ∫ᚱᚣ** — 27/05/2021
> but it still does not know the feilds


> **!!!!** — 27/05/2021
> hmm
> does it need to know the fields

> **ᚣ∫ᚱᚣ** — 27/05/2021
> it would know the type but not the fields

> **!!!!** — 27/05/2021
> because we can always add the fields once it's done

> **ᚣ∫ᚱᚣ** — 27/05/2021
> yes, to see if a function or field does/doesn't exist

> **!!!!** — 27/05/2021
> hmm
> well
> hmm
> one way might be to delay type checking the function bodies
> somehow
> like some Scope has a list of function bodies to type check at the end

> **ᚣ∫ᚱᚣ** — 27/05/2021
> thats what i was thinking
> but like
> as i stated before
> that would require a `.end` like thing
> which we dont have

> **!!!!** — 27/05/2021
> we might as well add it
> since it'd be useful for keeping track of unused types/variables

> **ᚣ∫ᚱᚣ** — 27/05/2021
> fair enough
> ill start to add it
> also should we make it so that you have to specify you want to > have to call the `.end` function
> because that would be useful in not accidentially messing up other code

> **!!!!** — 27/05/2021
> yeah
> hmm
> how to detect accidentally not calling .end

> **ᚣ∫ᚱᚣ** — 27/05/2021
> mmm

> **!!!!** — 27/05/2021
> We could use `with`
> ![python documentation about with](https://cdn.discordapp.com/attachments/710936824121655396/847623470749057044/unknown.png)

> **ᚣ∫ᚱᚣ** — 27/05/2021
> we would also have to go through every command and change it to > work with the .end thing now
> f;jlkdsafj;slkjgsklgj;lksgj;skl
> annoy

> **!!!!** — 27/05/2021
> because files from open also need to be closed
> hmm
> well
> not every command creates a new scope I think

> **ᚣ∫ᚱᚣ** — 27/05/2021
> but you might want to hold off on it throwing errors until later
> thats the problem

[2021-05-27](https://discord.com/channels/710932856251351111/710936824121655396/847621512831828009)

**Comment by SheepTester** [comment]
In summary:

1. Create the class type and constructor type before type checking the class body (this just involves moving some lines up)
2. Add a `.end` method to Scope and call it whenever the Scope ceases to be used. For debugging purposes, we can keep track of a global list of Scope instances where `.end` has not been called, then raise an error if there are still unended Scope instances.
3. Defer function expression type checking until the end by having a list property under Scope containing function expressions to type check at the end
