### ISSUE TITLE
Allowing for API usage of N

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#159]
## API Usage
What I am proposing is that instead of automatically running the program and outputting the errors to console, we allow `n.py` to be imported and used to parse files and return the errors that it has found, sort of like an API, here is an example of how that would work:
```py
import n
out = n.parse_text("let i:int = \"Oh, no, I cause an error\"") # out can maybe be a Scope
for i in out.errors:
  print("oops!")
```
This can be used to great effect in IDEs as they can now run compile-time and catch errors quickly as opposed to having to modify the code present on GitHub every update to fit their needs.
## Implementation
The way that this can be implemented is very simple in the `python` branch, we can simply do:
```py
if __name__ == "__main__":
```
This will stop the code in the if statement from running if the program was imported, allowing for it to be used as an API for other projects, overall increasing the usefulness of N, as if it is compatible with more IDEs, more people will use it because it is easier to use.

**Comment by Ashvin-Ranjan** [comment]
This should probably be done last.

**Comment by SheepTester** [comment]
You'll be pleased to know that #196 also made it possible to programmatically run N. It's used in type_check_test.py to run the type checking tests.

https://github.com/nbuilding/N-lang/blob/68978cba41951a7582f9f8d54129462c00e49ca4/python/type_check_test.py#L7

https://github.com/nbuilding/N-lang/blob/68978cba41951a7582f9f8d54129462c00e49ca4/python/type_check_test.py#L17-L19

`run_file` synchronously runs the N code at the given file path and then returns either None if everything went well or a string containing a list of human-readable errors

**Comment by Ashvin-Ranjan** [comment]
Should be done
