### ISSUE TITLE
Add docstrings

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#167]
Docstrings are very useful in helping other people understand our code and could help with new contributors.

**Comment by SheepTester** [comment]
What would this involve for the N interpreter?

I think we can use Rust's `///` convention:
```rust
/// Adds two numbers
let sum = [a:int b:int] -> int {
```

**Comment by SheepTester** [comment]
Oh is this for N or for the interpreter's code?

**Comment by Ashvin-Ranjan** [comment]
Yeah, this is for the interpreter code

**Comment by SheepTester** [comment]
Adding Python label even though the JS branch could also do with some documentation :lemonthink:

**Comment by Ashvin-Ranjan** [comment]
Idk if this is really needed
