### ISSUE TITLE
`[]` in N

### ISSUE THREAD

**Issue by ky28059** [nbuilding/N-lang#208]
I have recently been informed that the way to access a list at an index in N is
```js
let x = list |> itemAt(int) |> default([])
```
This is obviously bad and terrible and bad. For reference, most languages have it like 
```js
let x = list[int] ?? []
```
which I believe to be much cleaner, especially for something that comes up as often as getting the index of a list. 
If you want to be even cooler, you can be like kotlin and have `[]` be an overload for `.get()` similar to how `+` is an overload for `.plus()` and `==` for `.equals()`, etc. which allows it to work for maps and other data structures.
```kt
val x = mapOf("blah" to "wow")
val y: String? = x["blah"]
val z: String? = x["wow"]
```
You can keep the current behavior of returning a `maybe[]` as well.

**Comment by bayrongutierrez** [comment]
ممكن حسابات فري فاير

**Comment by SheepTester** [comment]
For reference,

- Discussion starts https://discord.com/channels/710932856251351111/710936824121655396/861079050239606834
- We consider the idea starting https://discord.com/channels/710932856251351111/710936824121655396/861082889051045910

To avoid an ASI problem like what happened in JS, we should disallow a newline between the value and the square brackets:

```ts
// Not valid syntax
let item = list
  [index]
```

This is to avoid an ambiguity like

```ts
// Is this the same as `let item = list; print([index])` or `let item = print(list[index])`?
let item = list
[index]
  |> print
```

We can consider this to be a binary operator, so it could accept the following types:

```elm
[t] list[t] -> int -> maybe[t]
[k, v] map[k, v] -> k -> maybe[v]
[t] maybe[list[t]] -> int -> maybe[t]
[k, v] maybe[map[k, v]] -> k -> maybe[v]
```

The first two will allow it to be used on lists and maps, and the latter two are just for convenience for chaining:

```ts
// Where `grid` is of type `list[list[int]]`
let cell = grid[y][x]
// Note that `grid[y]` returns a `maybe[list[int]]` but we can still use the `...[...]` operator on it
```

Is there a nicer name for this operator? I think Python calls it "subscripting"

**Comment by ky28059** [comment]
Ooh, I like the idea for `[]` to also chain on `maybe`s. Would be a step up from 
```js
obj?.[heavily]?.[nested]?.[property]
```

**Comment by SheepTester** [comment]
Presumably, we can't allow a newline between the value and the `[...]` because it'd be a syntax ambiguity

```ts
let first = list
[0]
  |> print
```

But should we allow a newline if it's inside parentheses? Like,

```ts
let first = (
  listWithARemarkablyLongName
    [anIndexWithASimilarlyLongName]
) |> print
```

**Comment by SheepTester** [comment]
Oh, should we also support indexing characters from strings?
