### ISSUE TITLE
When `onMessage` returns true it does not close the websocket

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#221]
This is because there is a `break`, instead of `websocket.close()`, this is an easy fix.

**Comment by SheepTester** [comment]
> this is an easy fix.

Have you jinxed yourself :eyes:

**Comment by SheepTester** [comment]
For your example, (am running this in `bug-fix` ebebb9e8a15afb9d0784602ca84c45fc1d7e1adc)

```ts
import times
import websocket // Used for connecting to WebSockets

let pub main = () |> ([] -> cmd[()] {
	let websocketTest = websocket.connect({
		onOpen: [send: websocket.send] -> cmd[bool] {
			print("Open!")
			let _ = send("hi")!
			while (true) {
				let _ = times.sleep(10000)!
			}
			return true
		}
		onMessage: [send: websocket.send message: str] -> cmd[bool] {
			print(message)
			let _ = send("hello")!
			return message == "hello"
		}
	}, "wss://echo.websocket.org")!
})
```

It appears to do the following:

- Connection opens.
- `onOpen` prints `Open!`.
- `onOpen` sends `hi` then asynchronously sleeps indefinitely.
- The server sends `hi` back.
- N's native websocket module runs `onMessage` given `hi`.
- `onMessage` prints `hi`.
- `onMessage` sends `hello`.
  - Asynchronously, the server sends `hello` back. The Python `websockets` library queues this in the async iterator of messages.
- `onMessage` returns `False`.
- N's native websocket module runs `onMessage` given `hello` as given by the Python library's async iterator.
- `onMessage` prints `hello`.
- `onMessage` sends `hello`.
  - Asynchronously, the server sends `hello` back. This is also queued.
- `onMessage` returns `True`.
- The N websocket module thus closes the websocket connection. This is correct behaviour.
- However, there's another `hello` message queued. We don't break the loop, so we continue and run `onMessage` on the remaining queued messages, in this case given `hello`.
- `onMessage` prints `hello`.
- `onMessage` sends `hello`. However, the websocket connection is closed, so this raises a runtime exception.

**Comment by SheepTester** [comment]
So the question is whether we should call `onMessage` on queued received messages after `onMessage` requests that the connection be closed. If so, then we can just break out of the loop on close.

**Comment by SheepTester** [comment]
Also, regardless, it'll still be possible to call `send` after the websocket connection closes (eg using `parallel`). This should not throw a runtime exception.

Ideally, had we had better foresight, we should've made `send` return a `cmd[result[(), err]]` where `err` is some error type (maybe it could just be some unspecified type that can't be read directly in N). However, `send` returns a `cmd[()]`, so we can't really do anything about it if we want to preserve backwards compatibility. (Unless we want to consider this a bug and fix its type signature.)

It probably should be fine if `send` silently ignores errors. What do you think?

**Comment by SheepTester** [comment]
So if we choose to discard queued messages after `onMessage` decides to close the websocket connection, this should be a fairly trivial fix. We can just `break` out of the loop after closing it.

https://github.com/nbuilding/N-lang/blob/ebebb9e8a15afb9d0784602ca84c45fc1d7e1adc/python/libraries/websocket.py#L119-L120

```py
                        if close:
                            await websocket.close()
                            break
```

We can silently ignore errors from sending to a closed websocket connection by `try`-`except`ing it.

https://github.com/nbuilding/N-lang/blob/ebebb9e8a15afb9d0784602ca84c45fc1d7e1adc/python/libraries/websocket.py#L93-L98

```py
            async def send_msg(message):
                if debug:
                    print(
                        f"[{url}] {Fore.CYAN}send{Style.RESET_ALL} {Fore.GREEN}{message}{Style.RESET_ALL}"
                    )
                try:
                    await websocket.send(message)
                except:
                    # Ignore all runtime errors (eg when attempting sending to a closed websocket)
                    pass
```

**Comment by Ashvin-Ranjan** [comment]
Why can't we amend send to be a `cmd[result[(), err]]` as most people discard the value anyways and don't bother to type it, it does break backward compatibility but it is such a niche case that I think it does not matter.

**Comment by Ashvin-Ranjan** [comment]
My take on this is as so:
- Change `send` to be a `cmd[result[(), err]]`
- Don't queue messages after `onMessage` requests a disconnect

**Comment by SheepTester** [comment]
I agree. In that case, what should the error type be? We have several options:

- We could make the error type `()` as well, as if to say, "There is only one error that can occur, and that is the sinister ***Error***." This should be pretty easy to do.
  - An alternative to `result[(), ()]` is just `bool`, but perhaps `err()` is more clearly an error than `false` or `true`
- We could make it a `str` and use the error message from the Exception thrown. This should be pretty easy to do as well.
- We could make it an enum type kind of like `json.value`, where each error is a type of error that could be thrown. That way N code can deal with each error on a case by case basis.
- We could make a special custom opaque type such that it can't be read directly by N code. This gives us room to change it in the future.

**Comment by Ashvin-Ranjan** [comment]
I feel like, for the sake of simplicity we should actually make it a `result[int, err]` as then we can pass the error code along with it.

**Comment by SheepTester** [comment]
What would the error code be?

By the way, the first type variable for `result` is the value for when sending is successful. Presumably `send` doesn't return anything useful so it can just be `()`

**Comment by Ashvin-Ranjan** [comment]
Oh ok, than yeah `result[(), err]` is best

**Comment by SheepTester** [comment]
> Oh ok, than yeah `result[(), err]` is best

He refers to these:

![image](https://user-images.githubusercontent.com/22133785/126055312-a1e83a5f-52dc-4950-b54e-98a969366a09.png)

per https://github.com/Luka967/websocket-close-codes

with JS also has which I guess is fine

**Comment by SheepTester** [comment]
Perhaps we can have `onOpen` and `onMessage` continue running in parallel (since they are already) after `connect` resolves, which can happen when the websocket closes

I'll have to look into it more but presumably instead of `await`ing the tasks for `onOpen` and `onMessage`, we can await a Python Future and then resolve that future when we close the websocket

**Comment by SheepTester** [comment]
So we can probably change

https://github.com/nbuilding/N-lang/blob/ebebb9e8a15afb9d0784602ca84c45fc1d7e1adc/python/libraries/websocket.py#L148-L152

to

```py
            on_close = asyncio.Future()
            
            asyncio.create_task(on_message())
            asyncio.create_task(on_connect())

            await on_close
            await on_close
```

and then whenever we close the websocket, we can use the [`set_result`](https://docs.python.org/3/library/asyncio-future.html#asyncio.Future.set_result) method to resolve the Future.

https://github.com/nbuilding/N-lang/blob/ebebb9e8a15afb9d0784602ca84c45fc1d7e1adc/python/libraries/websocket.py#L133-L136

```py
                    if isinstance(close, Cmd):
                        close = await close.eval()
                    if close:
                        await websocket.close()
                        on_close.set_result() # NOTE: I'm not sure if this requires the parameter to be given
```

**Comment by SheepTester** [comment]
From around [this message](https://discord.com/channels/710932856251351111/710936824121655396/866176100559618078) it appears discord.n's `times.sleep` is taking more than 45 seconds after the connection is closed. I guess that's the next bug to fix

**Comment by SheepTester** [comment]
![image](https://user-images.githubusercontent.com/22133785/126271249-a68186dc-d3e1-4d15-bbb7-4da6229a9c13.png)
Yet here it seems the program just exits

```ts
import times
import websocket // Used for connecting to WebSockets

let pub main = () |> ([] -> cmd[()] {
	let websocketTest = websocket.connect({
		onOpen: [send: websocket.send] -> cmd[bool] {
			print("Open!")
			let _ = send("hi")!
			let i = 0
			while (true) {
				let _ = times.sleep(1000)!
				var i = i + 1
				print(i)
				let _ = send(intInBase10(i))!
			}
			return true
		}
		onMessage: [send: websocket.send message: str] -> cmd[bool] {
			print(message)
			return message == "3"
		}
	}, "wss://echo.websocket.org")!
	print("The connection closed.")
	let _ = times.sleep(2000)!
	print("Bye!")
})

````

prints

```
Open!
hi
1
1
2
2
3
3
The connection closed.
4
5
Bye!
```

**Comment by SheepTester** [comment]
The issue was that Ash was using `N_WS_DEBUG=experimental` it appears
