### ISSUE TITLE
Add features from TypeScript

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#225]
Things to add (May be changed in the future):
- [x] `none` being falsey
- [x] `?` record access operator
- [x] `??` as alias for `default` (might be changed to `|`)
- [x] ~~Add enums for values\*~~
- [x] ~~Allow for `maybe` typed fields in records to be ommitted~~ (unable to exist with the current system)

\*Example:
```ts
type Test = "a" | "b" | "c"
```

**Comment by SheepTester** [comment]
> * `?` record access operator

Could you clarify this?



> * `none` being falsey

Hmm, would this just be overloading `|`? (ie, it's the same as item 3)



> * Add enums for values*

Why not just do

```ts
type test = a | b | c
```

**Comment by Ashvin-Ranjan** [comment]
> > * `?` record access operator
> 
> Could you clarify this?

Something like
```js
element.possiblyNullValue?.value
```
if `element.possiblyNullValue` is `none` then `value` is `none`, otherwise `value` is whatever it is

> > * `none` being falsey
> 
> Hmm, would this just be overloading `|`? (ie, it's the same as item 3)

Eh, I think that `~~possiblyNullValue` would be nice if the type is a `maybe` of anything other than a `bool`

> > * Add enums for values*
> 
> Why not just do
> 
> ```ts
> type test = a | b | c
> ```

What if you want to do
```ts
type test = a | b | c

type test2 = c | d | e
```
then what is `c`?

**Comment by SheepTester** [comment]
Couldn't you do `possiblyNullValue /= none`? `~~possiblyNullValue` seems quite cryptic to me

**Comment by SheepTester** [comment]
> What if you want to do
> 
> ```ts
> type test = a | b | c
> 
> type test2 = c | d | e
> ```
> 
> then what is `c`?

You can already try that in N 1; the second one should be an error because `c` was already defined. We could avoid namespace conflicts by creating a record instead, so `type test = ...` would also create a variable `test` of type `{ a: test; b: test; c: test }`

> * `none` being falsey

I'm against this. We should not encourage poor programming practices such as `~~maybe`.

**Comment by SheepTester** [comment]
> > > * `?` record access operator
> > 
> > 
> > Could you clarify this?
> 
> Something like
> 
> ```js
> element.possiblyNullValue?.value
> ```

(For the record) This has been moved to its own issue, #263

**Comment by SheepTester** [comment]
> * Allow for `maybe` typed fields in records to be ommitted

Based on the wording of this, I will not add
```ts
assert type { field: "yes" } : { field: maybe[str] }
```
to the tests since it is not specified by the issue

**Comment by SheepTester** [comment]
> * `?` record access operator

See #264
