### ISSUE TITLE
`parallel` causes runtime error when function does not use `!`

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#227]
This is because it does `.eval`, which won't happen if it does not use `!`

**Comment by SheepTester** [comment]
Which function? Who does `.eval`? Who might not use `!`?

If `parallel` is the one doing `.eval`, I think `parallel` is correct. The type system should guarantee that `parallel` is given a Python `ncmd.Cmd`. Evidently if a function that is supposed to return an N `cmd` and doesn't use `!` doesn't return a Python `ncmd.Cmd` during runtime, then there's something wrong about that function.
