### ISSUE TITLE
Add deprecation notice to `itemAt` and `getItem`

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#229]
Add a deprecation system for Native Functions as well.

**Comment by SheepTester** [comment]
Well, these two functions in particular might still have a use. For example, `itemAt(0)` can be used with a map function to get the first items of each list in a list. Because N's function expressions are so verbose, it's certainly nicer to write

```ts
nestedList |> map(itemAt(0))
```
than
```ts
nestedList |> map([list:list[int]] -> maybe[int] { return list[0] })
```

**Comment by Ashvin-Ranjan** [comment]
Fair, I will close this
