### ISSUE TITLE
`while` requires a `value`, not an `expression`, which makes certain situations seem like weird errors

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#237]
```js
while (~test) {
    // some code
}
```
will not parse as `~test` is an expression so it has to be wrapped in parenthesis, leading to strange occurrences such as:
```js
while ((~test)) {
    // some code
}
```
which is very confusing.

**Comment by SheepTester** [comment]
Presumably the fix here is just to replace `value` with `expression` in syntax.lark, right?

Is there already a test for this in the syntax tests? Maybe we should add this as a test to make sure it doesn't happen again
