### ISSUE TITLE
Define behaviours for `round` etc. for odd float values

### ISSUE THREAD

**Issue by SheepTester** [nbuilding/N-lang#243]
Technically this is a new "feature" because the behaviour of these functions aren't defined for these extreme values yet. 😳

`round`, `floor`, and `ceil` are supposed to convert floats to ints. The Python branch uses the built-in analogous functions, but they raise a runtime error for some float values.

Here's how `round` deals with various float values in Python.

```py
>>> inf = 1 / 5e-324
>>> nan = inf - inf
>>> round(inf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: cannot convert float infinity to integer
>>> round(nan)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: cannot convert float NaN to integer
>>> round(-inf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: cannot convert float infinity to integer
>>> round(-0.0)
0
>>> round(1.7976931348623157e+308)
179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
```

Here's how JS converts them to integers, using various methods.
![image](https://user-images.githubusercontent.com/22133785/126932936-56a8546a-f1fa-4753-b26c-a4bd377940e2.png)

I propose we convert the infinities and NaN to 0. What do you think?

**Comment by Ashvin-Ranjan** [comment]
I do agree with this sentiment
