### ISSUE TITLE
Define what whitespace characters `strip` removes

### ISSUE THREAD

**Issue by SheepTester** [nbuilding/N-lang#245]
The Python implementation uses [`strip`](https://docs.python.org/3/library/stdtypes.html#str.strip) which doesn't specify what whitespace characters it removes. This means we can't rely on it.

[JS `trim`](https://tc39.es/ecma262/multipage/text-processing.html#sec-trimstring) removes the following characters: tab, vertical tab, form feed, space, non-breaking space, zero-width non-breaking space, line feed, carriage return, line separator, paragraph separator, and other characters in the Unicode "Space_Separator" general category. We can probably find a list of those other characters.

**Comment by SheepTester** [comment]
Per https://discord.com/channels/710932856251351111/710936824121655396/869078458716811304

> It should remove all new lines, tabs, and spaces from either end of a string

So the list is just `\n\t `

**Comment by Ashvin-Ranjan** [comment]
it appears that JS `trim` may be the best defined way

**Comment by Ashvin-Ranjan** [comment]
> Per https://discord.com/channels/710932856251351111/710936824121655396/869078458716811304
> 
> > It should remove all new lines, tabs, and spaces from either end of a string
> 
> So the list is just `\n\t `

we should maybe use what js `trim` uses because it is more well defined

**Comment by SheepTester** [comment]
Sure
