### ISSUE TITLE
Scope object is printed at the end of execution

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#257]
This is because of the check `if errors is not None`, which causes the scope to print out at the end.

**Comment by SheepTester** [comment]
Are you referring to this?
https://github.com/nbuilding/N-lang/blob/73b46b079737170dc66912eb18ae917f2ddb1a3f/python/n.py#L207-L209


> `if errors is not None`

Wow, Python really does read like psuedocode
