### ISSUE TITLE
Async does not work with N executable

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#70]
This appears to only occur in the executable of N, as it is most likely a problem with `pyinstaller` or the tool I am using to create the executable

This does occur on Windows, but it is not confirmed yet whether it occurs on the Mac version too.

Here is the error readout
```
Traceback (most recent call last):
  File "n.py", line 123, in <module>
  File "asyncio\base_events.py", line 642, in run_until_complete
  File "n.py", line 101, in parse_tree
AttributeError: 'Cmd' object has no attribute 'eval'
[9760] Failed to execute script n
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Function.run.<locals>.run_command() running at function.py:35> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002339C7EAD30>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Function.run.<locals>.run_command() running at function.py:35> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002339CBC7970>()]>>
```

We have deduced that it is an error with the async as this occurred when testing [discord.n](https://github.com/nbuilding/discord.n), which is every async heavy.

**Comment by SheepTester** [comment]
Seems to be where it runs the main `cmd` exported from the main file

https://github.com/nbuilding/N-lang/blob/6877ee22440b9feb8dd18eb179835c77e00ca2bf/python/n.py#L99-L102

It's very curious because `Cmd` *should* have an `eval` method; maybe it doesn't support async methods? Idk

https://github.com/nbuilding/N-lang/blob/6877ee22440b9feb8dd18eb179835c77e00ca2bf/python/cmd.py#L28

**Comment by Ashvin-Ranjan** [comment]
After doing some research I have found [Issue #4942](https://github.com/pyinstaller/pyinstaller/issues/4942) on the PyInstaller GitHub repo that talks about `aiohttp` issues, and after looking into this we may need to follow what is in the [Wiki Page](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing) about Multiprocessing

**Comment by SheepTester** [comment]
Why isn't this in N 1.2? Isn't this a blocker for release?

**Comment by SheepTester** [comment]
> `AttributeError: 'Cmd' object has no attribute 'eval'`

This is very strange because if it's a `Cmd`, it should have `eval`. Perhaps async methods get removed by the compiler thing?
