### ISSUE TITLE
Type checker does not require returning

### ISSUE THREAD

**Issue by SheepTester** [nbuilding/N-lang#79]
It is currently valid to simply do

```ts
let isNone = [maybeStr: maybe[str]] -> bool {
  let output = if let <yes _> = maybeStr {
    true
  } else {
    false
  }
}

print(isNone(none))
```

(I haven't tested this)

The above snippet I believe causes a nasty runtime error because the function returns Python's `None`.

**Comment by Ashvin-Ranjan** [comment]
Should this cause a Syntax Error or a Compile Time Error?

**Comment by SheepTester** [comment]
> Should this cause a Syntax Error or a Compile Time Error?

Compile time since the return statements could be inside if statements, for example
