### ISSUE TITLE
Keywords can be used as an identifier

### ISSUE THREAD

**Issue by SheepTester** [nbuilding/N-lang#80]
This prevents the use of parentheses after `return` for returning a value (as opposed to calling a function named `return`).

```ts
let return = [let: int] -> int {
  print(let)
}
print(return(3))
```

This prints `3` then `[unprintable value]` (Python `None`)

However, fixing this could break backwards compatibility.

**Comment by Ashvin-Ranjan** [comment]
To fix this and keep backward compatibility we add an optional `:` (or something else) to `return` that is required if you are returning a tuple, this change would work because it only affects returning tuples and that is what is broken in the earlier version so no one would be affected

**Comment by SheepTester** [comment]
We could also declare this behaviour a bug and not worry about backwards compatibility 😎

**Comment by Ashvin-Ranjan** [comment]
true

**Comment by Ashvin-Ranjan** [comment]
If we are going to call this a bug then we can just make some simple changes to the parser to allow for this.

**Comment by SheepTester** [comment]
Perhaps we should also reserve some other keywords for the future, such as `match`?

**Comment by Ashvin-Ranjan** [comment]
Sounds like a good idea here is a list of keywords I think we should reserve:
- `return`
- `if`
- `else`
- `for`
- `match`
- `when`

If you have any more to add then just tell me

**Comment by SheepTester** [comment]
Here's a list of all the keywords in N so far, for reference: `var` `let` `type` `alias` `for` `in` `import` `imp` `return` `if` `else` `class` `pub` `_` (the last one is used for discarding values; its specialty is that you can do multiple `let _ =`s without getting an error about a variable already existing with the same name)

**Comment by Ashvin-Ranjan** [comment]
Sounds good, I'll make a pr with the new syntax
