### ISSUE TITLE
Syntactical ambiguity when assigning a variable to a pipe output in a function

### ISSUE THREAD

**Issue by SheepTester** [nbuilding/N-lang#81]
```ts
let main = [_: ()] -> () {
    let results: list[result[int, str]] = [err("sad"), ok(2), err("wow")]

    let errors = filterMap(
        [result: result[int, str]] -> maybe[str] {
            return if let <err error> = result {
                yes(error)
            } else {
                none
            }
        },
        results
    )
        |> err

    print(errors)
}

main(())

```

The above code inconsistently alternates between logging a function (presumably `filterMap`) and `<err ["sad", "wow"]>`.

![image](https://user-images.githubusercontent.com/22133785/109730034-abdd7080-7b6d-11eb-9281-78484e52cbc7.png)

Adding a type annotation `result[int, list[str]]` can produce the following error:

```
Error: You set errors, which is defined to be a result[int, list[str]], to what
evaluates to a (a -> maybe[b]) -> list[a] -> list[b].
  --> run.n:4:42
 4 |     let errors: result[int, list[str]] = filterMap(
                                              ^^^^^^^^^
Ran with 1 error and 0 warnings.
```

**Comment by Ashvin-Ranjan** [comment]
I think that we should probably make the `|>` operator bind tighter, this should be a simple change to the parser

**Comment by SheepTester** [comment]
Binding tighter might have the opposite effect because if it binds tighter than function calling, then it'll StEAL the function arguments: `wow; ((arg1, arg2) |> unepic)`

I wonder why it would make the expression separate, though, since there's no semicolon or newline between the function name and its arguments

**Comment by Ashvin-Ranjan** [comment]
Turns out the problem was with `code_block` as it did not need any separation between instructions.
