### ISSUE TITLE
Suggested features to add from Kotlin

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#85]
Kevin has compiled a [gist](https://gist.github.com/ky28059/09feab45f70c6a83677458de7e27f2c5) of all of the things that are interesting in Kotlin that we may adopt

- [x] Inferring
- [x] Ranges
  - [x] `..` operator
  - [x] `until` operator
  - [x] `step` operator
  - [x] `downTo` operator
- [x] `in` operator
- [x] Destructuring
- [x] Destructuring in `for` loops
- [x] `when` statement (see #161)
- [x] `match` statement (see #78)
- [x] `to` operators for tuples
- [x] Expressions able to be evaluated everywhere
- [x] `if`, `else`, and `else if` can all be expressions
- [x] Primary constructors
- [x] ~~Contructors able to be defined in classes~~
- [x] `==` does not compare memory location
- [x] ~~`vararg` or something similar~~

**Comment by SheepTester** [comment]
Destructuring in `for` loops already is a thing because we've abstracted assigning a pattern to a type/value.

`==` checks by value not memory location already

> Expressions able to be evaluated everywhere

We already have this, I think; all expressions can be used where values are expected.

> `when` statement (or `switch` statement)

this would be the `match` proposal: #78

**Comment by Ashvin-Ranjan** [comment]
Ok, I have updated the list with that info

**Comment by ky28059** [comment]
The to operator actually creates a pair, if you're interested in implementing that
![image](https://user-images.githubusercontent.com/60120929/110004246-13113700-7ccc-11eb-84eb-f080fea06693.png)

**Comment by Ashvin-Ranjan** [comment]
Oh ok, I shall update it, the thing I dislike using words in code so I kinda want to use something like `~>` but that might just be bad

**Comment by SheepTester** [comment]
> The to operator actually creates a pair, if you're interested in implementing that
> [image](https://user-images.githubusercontent.com/60120929/110004246-13113700-7ccc-11eb-84eb-f080fea06693.png)

Oh, in that case, we already have something like that. `mapFrom([(1, "hi"), (2, "hey")])`

**Comment by Ashvin-Ranjan** [comment]
True, so I guess that `to` is effectively implemented.

**Comment by ky28059** [comment]
> > The to operator actually creates a pair, if you're interested in implementing that
> > [image](https://user-images.githubusercontent.com/60120929/110004246-13113700-7ccc-11eb-84eb-f080fea06693.png)
> 
> Oh, in that case, we already have something like that. `mapFrom([(1, "hi"), (2, "hey")])`

Hmm, not the biggest fan of the surrounding square brackets. Does N have `vararg` or something equivalent?

**Comment by Ashvin-Ranjan** [comment]
Ok, Added it to the list to implement.

**Comment by SheepTester** [comment]
What did I do

**Comment by ky28059** [comment]
Will N have null safety?

**Comment by SheepTester** [comment]
> Will N have null safety?

Already does with the maybe type

**Comment by ky28059** [comment]
Is the maybe type something like `maybe<int>` like kotlin's `Int?` or is it more like kotlin's `Any?`?

**Comment by SheepTester** [comment]
`maybe[int]` is like Kotlin's `Int?`

**Comment by SheepTester** [comment]
What if we did something like

```ts
identifier[1, 2, 3]
//       ^ no newlines allowed between the identifier and list
```

as a shorthand for `identifier([1, 2, 3])`: calling a function with a list as an argument.

If other arguments need to be given, we can just take advantage of currying:

```ts
coolFunction("happy", \{s})[1, 2, 3](true)
```

**Comment by Ashvin-Ranjan** [comment]
Intresting, that might be nice.

**Comment by Ashvin-Ranjan** [comment]
Should the `vararg` idea be removed because it can be done with a `record` or a `tuple`?

**Comment by SheepTester** [comment]
yeah, or a list

**Comment by Ashvin-Ranjan** [comment]
Closed as all things here are done
