### ISSUE TITLE
request.get returns record with a feild called return

### ISSUE THREAD

**Issue by Ashvin-Ranjan** [nbuilding/N-lang#97]
This is a problem because as of fixing #80 getting this field will cause a syntax error.

As an example, this is taken from the `identify` branch if `discord.n`:
```js
let pub getMessage = [c:str m:str] -> cmd[maybe[message.Message]] {
	let url:str = "https://discord.com/api/channels/" + c + "/messages/" + m
	let r = request.get(url, header)!

	if r.code /= 200{
		return none
	}

	return parseMessageData(r.return)
}
```
And this will end up creating a syntax error on `return parseMessageData(r.return)`

**Comment by SheepTester** [comment]
Should we allow keywords in record field names? The only place where they'd be used is

```ts
let { return: ok }: { return: str } = { return: "hi!" }
//    ^^^^^^          ^^^^^^            ^^^^^^
```

and

```ts
myRecord.return
//       ^^^^^^
```

We could alternatively only allow a certain subset of keywords for field names.

By the way, is it currently possible for numbers to end in a decimal point (like `3.`)? If so, then infix operators may have to be excluded, such as `3.in(something)` which could either be that or `3. in something`

**Comment by Ashvin-Ranjan** [comment]
That would require some weird edits to the code which might make some really weird edge cases later down the line

**Comment by SheepTester** [comment]
> That would require some weird edits to the code which might make some really weird edge cases later down the line

Perhaps it may not be so bad if in those cases, we just define it like

```lark
all_identifiers: NAME
               | "return"
               | "let"
               # ...
```

**Comment by Ashvin-Ranjan** [comment]
We can just use CNAME which is what we had as `NAME` before so it should not be too bad hopefully

**Comment by SheepTester** [comment]
🙏
